### ISSUE TITLE
Dictionary missing too many words

### ISSUE THREAD

**Issue by ColonelJ** [AravindhStanley/wordle-clone-python#2]
Very basic words such as 'stale' are missing.  Please find attached a more complete dictionary: [five_letter_words.txt](https://github.com/AravindhStanley/wordle-clone-python/files/8100549/five_letter_words.txt).  Got the list from [wordfind.com](https://wordfind.com/length/5-letter-words/).

**Comment by ColonelJ** [comment]
Though that list is missing words such as 'erect' which are in your current list, so I would merge the lists.

**Comment by aravindh-murugesan** [comment]
Yeah, I'm aware of the missing words. I will fix it.

**Comment by aravindh-murugesan** [comment]
Updated word list. Sourced it from the original wordle game. So it should cover everything the original game does.
